name: podtastic
description: A podcast player

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  sqflite: ^1.1.0

  http: ^0.12.0+1

  html: ^0.13.3+3

  audioplayers: ^0.13.2

  flutter_html: ^0.8.2

  xml: ^3.4.0

  webfeed: ^0.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AbrilFatface
      fonts:
        - asset: fonts/Abril_Fatface/AbrilFatface-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/Playfair_Display/PlayfairDisplay-Black.ttf
        - asset: fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf
        - asset: fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
        - asset: fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf
        - asset: fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
        - asset: fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
    - family: BigShouldersDisplay
      fonts:
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-Black.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-Bold.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-ExtraBold.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-Light.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-Medium.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-Regular.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-SemiBold.ttf
        - asset: fonts/Big_Shoulders_Display/BigShouldersDisplay-Thin.ttf
    - family: Spectral
      fonts:
        - asset: fonts/Spectral/Spectral-Bold.ttf
        - asset: fonts/Spectral/Spectral-ExtraBold.ttf
        - asset: fonts/Spectral/Spectral-Light.ttf
        - asset: fonts/Spectral/Spectral-Medium.ttf
        - asset: fonts/Spectral/Spectral-Regular.ttf
        - asset: fonts/Spectral/Spectral-SemiBold.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-Bold.ttf
        - asset: fonts/Rubik/Rubik-Black.ttf
        - asset: fonts/Rubik/Rubik-Medium.ttf
        - asset: fonts/Rubik/Rubik-Light.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
